objects/CIJob__c.object
<CustomObject>
    <fields>
        <fullName>AccelQCIJobId__c</fullName>
        <label>AccelQ CI Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIJobInstanceId__c</fullName>
        <externalId>true</externalId>
        <label>CI Job Instance Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>JobCompletedOn__c</fullName>
        <label>Job Completed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>JobStartedOn__c</fullName>
        <label>Job Started On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RunTimeAttributes__c</fullName>
        <label>Run Time Attributes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StatusUpdatedOn__c</fullName>
        <label>Status Updated On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestCasesFailed__c</fullName>
        <label>#Test Cases Failed</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TestCasesNotRun__c</fullName>
        <label>#Test Cases Not Run</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TestCasesPassed__c</fullName>
        <label>#Test Cases Passed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalTestCases__c</fullName>
        <label>#Total Test Cases</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CI Job</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Job #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccelQCIJobMonitoringService.cls
global with sharing class AccelQCIJobMonitoringService implements Database.batchable<sobject>,Database.AllowsCallouts , Database.Stateful{
    global final String Query;
    global  Map<string,string> tokens;
    global  string endPoint;
    global AccelQCIJobMonitoringService(){
        query = 'Select id,Project__c,Status__c,TotalTestCases__c,StatusUpdatedOn__c,JobStartedOn__c,JobCompletedOn__c,RunTimeAttributes__c,ParentId__c,CIJobInstanceId__c,AccelQCIJobId__c,TestCasesPassed__c,TestCasesNotRun__c,TestCasesFailed__c from CIJob__c where CIJobInstanceId__c != null and Status__c != \'Complete\'';              
        endPoint =  AccelQConnect.getEndpoint();
    }
    global AccelQCIJobMonitoringService(Map<string,string> tokens){
    	this();
        this.tokens =tokens;
    }
    
   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }  
    global void execute(Database.BatchableContext info, List<CIJob__c> jobs){
        try{
            If(tokens == null)  tokens = AccelQConnect.getAccessToken();
            for(CIJob__c job : jobs){
               AccelQConnect.monitorJob( endPoint , tokens , job );
            }
        }catch(Exception Ex){
            CommonServices.logError('AccelQJobInitiator batch', Ex);
        }
      
        
    }     
    global void finish(Database.BatchableContext info){   
       //do nothing
    } 
}