objects/CIJob__c.object
<CustomObject>
    <fields>
        <fullName>AccelQCIJobId__c</fullName>
        <label>AccelQ CI Job Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CIJobInstanceId__c</fullName>
        <externalId>true</externalId>
        <label>CI Job Instance Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RunTimeAttributes__c</fullName>
        <label>Run Time Attributes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CI Job</label>
    <nameField>
        <displayFormat>CI-{0}</displayFormat>
        <label>Job #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccelQCIJobInitiator.cls
global with sharing class AccelQCIJobInitiator implements Database.batchable<sobject>,Database.AllowsCallouts , Database.Stateful{
    global final String Query;
    global  Map<string,string> tokens;
    global final string endPoint;

    global AccelQCIJobInitiator(){
        query = 'Select id,Project__c,Status__c,RunTimeAttributes__c,ParentId__c,CIJobInstanceId__c,AccelQCIJobId__c from CIJob__c where CIJobInstanceId__c = null and Status__c = \'Created\'';
        endPoint =  AccelQConnect.getEndpoint();
    }
    global AccelQCIJobInitiator(Map<string,string> tokens){
          this();
        this.tokens = tokens;
      
    }
    
   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }  
    global void execute(Database.BatchableContext info, List<CIJob__c> jobs){
        try{
            system.debug('>>>> END POINT <<< ' + endPoint);
            If(tokens == null)  tokens = AccelQConnect.getAccessToken();           
            for(CIJob__c job : jobs){
               AccelQConnect.initiateJob( endPoint , tokens , job );
            }
        }catch(Exception Ex){
            CommonServices.logError('AccelQJobInitiator batch', Ex);
        }
      
        
    }     
    global void finish(Database.BatchableContext info){   
        List<CIJob__c> jobs = Database.Query(query);

        if(jobs.size() > 0){
            //Database.executeBatch( new AccelQCIJobInitiator() , 50 );
        }
    } 

}