objects/CIJobLogs__c.object
<CustomObject>
    <fields>
        <fullName>ClassProcessName__c</fullName>
        <label>Class / Process Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line__c</fullName>
        <label>Line #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CI Job Log</label>
    <nameField>
        <displayFormat>Log-{0}</displayFormat>
        <label>Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Job Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CommonServices.cls
public abstract with sharing class CommonServices {
    
    public static void logError( string classProcessName , Exception Ex){
        try{
            CIJobLogs__c log = new CIJobLogs__c();
            log.ClassProcessName__c = classProcessName;
            log.Type__c = Ex.getTypeName();
            log.Line__c = String.valueOf(Ex.getLineNumber());
            log.Message__c = Ex.getMessage();
            log.StackTrace__c = Ex.getStackTraceString();
            insert log;
        }catch(Exception logException){
            logError('CommonServices.logError' , logException);
        }        

    }
}